name: Taller CI/CD
run-name: Estamos ejecutando acciones automáticas

on: [push]


jobs:
    MiPrimeraAutomatizacion:
        runs-on: ubuntu-latest
        steps:
            - name: Vamos a decir hola
              run: echo "Hola, esta es mi primera automatización con GitHub Actions"
            - name: ¿Quién soy?
              run: whoami
            - name: ¿Donde estoy?
              run: lsb_release -a
            - name: ¿Que tengo a la vista?
              run: ls .
            - name: ¿Que carpeta?
              run: pwd
            - name: Actualizamos repos..
              run: sudo apt update
            - name: Instalamos Programa critico
              run: sudo apt install -y cowsay
            - name: ¡Lo tengo! Vamos a ejecutarlo
              run: cowsay "Que deje de llover ya"