name: Taller CI/CD
run-name: Estamos ejecutando acciones autom√°ticas

on: [push]


jobs:
    MiPrimeraAutomatizacion:
        runs-on: ubuntu-latest
        steps:
            - name: Cargar los ficheros de mi repo
              uses: actions/checkout@v6
            - name: Instalar node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Instalar REPO
              run: npm install
            - name: Build REPO
              run: npm run build